src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;


#[ORM\Entity(repositoryClass: PostRepository::class)]
#[ORM\Table(name: "posts")]

class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?string $post_text = null;

    #[ORM\Column(type: 'integer')]
    private ?int $post_date = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\Column]
    private ?int $author_id = null;

    #[ORM\Column]
    private ?int $view_count = 0;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function getComments(): Collection
    {
        return $this->comments;
    }

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'posts')]
    #[ORM\JoinColumn(name: 'author_id', referencedColumnName: 'id', nullable: false)]
    private ?User $user = null;

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): static
    {
        $this->user = $user;
        $this->author_id = $user->getId();
        $this->author = $user->getLogin();
        return $this;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getPostText(): ?string
    {
        return $this->post_text;
    }

    public function setPostText(string $post_text): static
    {
        $this->post_text = $post_text;

        return $this;
    }

    public function getPostDate(): ?int
    {
        return $this->post_date;
    }

    public function setPostDate(): static
    {
        $this->post_date = time();

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getAuthorId(): ?int
    {
        return $this->author_id;
    }

    public function setAuthorId(int $author_id): static
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getViewCount(): ?int
    {
        return $this->view_count;
    }

    public function setViewCount(int $view_count): static
    {
        $this->view_count = $view_count;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('title', TextType::class, [
            'label' => 'Title',
            'attr' => ['class' => 'form-control', 'placeholder' => 'Enter the title'],
        ])
        ->add('post_text', TextareaType::class, [
            'label' => 'Content',
            'attr' => ['class' => 'form-control', 'rows' => 10, 'placeholder' => 'Write your post here...'],
        ])
    ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\PostRepository;
use App\Service\FavoriteService;
use App\Service\PostService;
use App\Service\CommentService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;

class PostController extends AbstractController
    {

    private PostService $postService;
    private CommentService $commentService;
    private FavoriteService $favoriteService;
    public function __construct(

        PostService $postService,
        CommentService $commentService,
        FavoriteService $favoriteService,
        EntityManagerInterface $entityManager,
    ) {

        $this->postService = $postService;
        $this->commentService = $commentService;
        $this->favoriteService = $favoriteService;
        $this->entityManager = $entityManager;
        }
    #[Route('/', name: 'post_list', methods: ['GET'])]
    public function index(PostRepository $postRepository, Request $request): Response
        {


        $page = $request->query->getInt('page', 1);
        $sort = $request->query->get('sort', 'latest');
        $limit = $request->query->getInt('limit', 3);
        $data = [
            'limit' => $limit,
            'page' => $page,
            'sort' => $sort
        ];
        $posts = $this->postService->sortPost($data);
        $totalPosts = $postRepository->getTotalCount();
        $totalPages = ceil($totalPosts / $limit);

        return $this->render('post/index.html.twig', [
            'posts' => $posts,
            'current_page' => $page,
            'total_pages' => $totalPages,
            'sort' => $sort,
        ]);
        }
    #[Route('/post_loadMore', name: 'post_load_more', methods: ['GET'])]
    public function loadMore(Request $request): Response
        {
        $limit = $request->query->getInt('limit', 3);
        $page = $request->query->getInt('page', 1);
        $sort = $request->query->get('sort', 'latest');

        $data = [
            'limit' => $limit,
            'page' => $page,
            'sort' => $sort
        ];
        $posts = $this->postService->sortPost($data);
        return $this->render('post/_posts.html.twig', [
            'posts' => $posts,
        ]);
        }
    #[Route('/post/{id}', name: 'post_show')]
    public function show(Post $post, Request $request, EntityManagerInterface $entityManager): Response
        {
        $ip = $request->getClientIp();
        // set count views to service 
        $this->postService->incrementViewCount($ip, $post->getId());

        $commentId = $request->request->get('comment_id');
        $comment = $commentId ? $entityManager->getRepository(Comment::class)->find($commentId) : new Comment();
        $comment->setPost($post);

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $this->commentService->handleComment($comment);
            return $this->redirectToRoute('post_show', ['id' => $post->getId()]);
            }

        $comments = $this->commentService->sortComments($post);
        $favorites = $this->favoriteService->isPostFavorited($post);

        return $this->render('post/show.html.twig', [
            'favorites' => $favorites,
            'post' => $post,
            'form' => $form->createView(),
            'comments' => $comments,
            'editingCommentId' => $commentId ? $commentId : '',
        ]);
        }
    #[Route('/post_edit/{id}', name: 'post_edit')]
    public function edit(Request $request, Post $post, EntityManagerInterface $entityManager): Response
        {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('post_list', [], Response::HTTP_SEE_OTHER);
            }

        return $this->render('post/post_edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
        }
    #[Route('/post_create', name: 'post_create', methods: ['GET', 'POST'])]
    public function create(Request $request, PostRepository $postRepository): Response
        {
        $post = new Post();
        $user = $this->getUser();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $post->setUser($user);
            $post->setPostDate();
            $postRepository->save($post, true);

            return $this->redirectToRoute('post_list');
            }

        return $this->render('post/create.html.twig', [
            'form' => $form,
            'post' => $post,
        ]);
        }
    #[Route('/{id}', name: 'app_post_delete', methods: ['POST'])]
    public function delete(Request $request, Post $post, EntityManagerInterface $entityManager): Response
        {
        if ($this->isCsrfTokenValid('delete' . $post->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($post);
            $entityManager->flush();
            }

        return $this->redirectToRoute('post_list', [], Response::HTTP_SEE_OTHER);
        }

    }

templates/post/_delete_form.html.twig
<form method="post" action="{{ path('app_post_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
	<button class="btn btn-danger">Delete</button>
</form>

templates/post/_posts.html.twig
<div class="row">
	{% for post in posts %}
		<div class="col-md-12 mb-4">
			<div class="card bg-dark text-white ">
				<div class="card-body">
					<a href="{{ path('post_show', { 'id': post.id }) }}" class="text-decoration-none text-white">
						<h5 class="card-title">{{ post.title }}</h5>
						<p class="card-text">{{ post.postText | slice(0, 100) ~ '...' }}</p>
						<p class="card-text">
							<small class=" text-white">Posted on
								{{ post.postDate | date('Y-m-d') }}</small>
							<br>
							<small class=" text-white">Views:
								{{ post.viewCount }}</small>
							<small class="text-white">
								Comments:
								{{ post.comments | filter(c => c.status == 'approved') | length }}
								/
								{{ post.comments | length }}
							</small>

						</p>
					</a>
				</div>
			</div>
		</div>
	{% endfor %}
</div>

templates/post/create.html.twig
{# templates/post/create.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Create Post
{% endblock %}

{% block body %}

	<h1>Create Post</h1>

	{{ form_start(form) }}
	    {{ form_row(form.title) }}
	    {{ form_row(form.post_text) }}
       <button type="submit" class="btn btn-dark">Save</button>

	 
	{{ form_end(form) }}

{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container mt-5">

		<div class="btn-group mb-3 " role="group" aria-label="Sort Options">
			<a href="{{ path('post_list', { sort: 'latest', page: 1 }) }}" class="btn btn-dark mt-2 me-2 {% if sort == 'latest' %}active{% endif %}">Latest</a>
			<a href="{{ path('post_list', { sort: 'popular', page: 1 }) }}" class="btn btn-dark mt-2  {% if sort == 'popular' %}active{% endif %}">Popular</a>
		</div>

		<div id="posts">
			{% include 'post/_posts.html.twig' %}
		</div>

		<nav aria-label="Page navigation">
			<ul class="pagination">
				{% if current_page > 1 %}
					<li class="page-item">
						<a class="btn btn-dark me-2" href="{{ path('post_list', { page: current_page - 1, sort: sort }) }}" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
						</a>
					</li>
				{% endif %}

				{% for page in 1..total_pages %}
					<li class="page-item {% if page == current_page %}active{% endif %}">
						<a class="btn btn-dark me-2" href="{{ path('post_list', { page: page, sort: sort }) }}">{{ page }}</a>
					</li>
				{% endfor %}

				{% if current_page < total_pages %}
					<li class="page-item">
						<a class="btn btn-dark me-2" href="{{ path('post_list', { page: current_page + 1, sort: sort }) }}" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					</li>
				{% endif %}
			</ul>
		</nav>

		{% if current_page < total_pages %}
			<button id="loadMore" data-page="{{ current_page + 1 }}" data-sort="{{ sort }}" class="btn btn-dark">Load More</button>
		{% endif %}
	</div>
	<script src="{{ asset('js/loadmore.js') }}"></script>
{% endblock %}

templates/post/post_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Post
{% endblock %}

{% block body %}
	<link rel="stylesheet" href="{{ asset('styles/post_create_edit.css') }}">
	<h1>Edit Post
		{{post.id}}
	</h1>

	{{ form_start(form) }}
	{{ form_row(form.title) }}
	{{ form_row(form.post_text) }}

	<button type="submit" class="btn btn-dark  ">Edit</button>

	{{ form_end(form) }}

	{{ include('post/_delete_form.html.twig') }}

{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ post.title }}
{% endblock %}

{% block body %}
	<div class="container mt-5">
		<h1>{{ post.title }}</h1>
		<p>{{ post.posttext }}</p>
		<p>
			<small>{{ post.author }}</small>
		</p>
		<p>
			<small>Posted on
				{{ post.postdate | date('Y-m-d') }}</small>
		</p>

		{% if is_granted('ROLE_ADMIN')  or  (is_granted('ROLE_EDITOR') and app.user == post.author)%}
			<a href="{{ path('post_edit', { 'id': post.id }) }}" class="btn btn-dark mt-2">Edit post</a>
		{% endif %}


		<h4 class="text-body mb-0">Comments ({{ comments|length }})</h4>
		<ul>
			{% for comment in comments %}
				<li>
					<strong>{{ comment.user.login }}</strong>
					said:
					{{ comment.text }}
					<br><small>Posted on
						{{ comment.commentdate | date('Y-m-d H:i') }}</small>

					{% if is_granted('ROLE_ADMIN') %}
						Status:
						{{ comment.status }}
						<a href="javascript:void(0);" class="btn btn-dark" onclick="editComment({{ comment.id }}, '{{ comment.text|e('js') }}', '{{ comment.status|e('js') }}')">Edit</a>
					{% endif %}
				</li>
			{% else %}
				<li>No comments yet.</li>
			{% endfor %}
		</ul>
		{% if app.user != null %}
			<h3>Leave a Comment</h3>

			<h6>Description: comments wait for admin approved</h6>

			{{ form_start(form) }}
			{{ form_row(form.text) }}
			{% if is_granted('ROLE_ADMIN') %}
				{{ form_row(form.status) }}
			{% endif %}
			<input type="hidden" id="comment_id" name="comment_id" value="{{ editingCommentId ? editingCommentId : '' }}">
			<button type="submit" class="btn btn-dark mt-1">{{ editingCommentId ? 'Update Comment' : 'Add Comment' }}</button>
			{{ form_end(form) }}
			
			{% if favorites %}
				<form id="removefavorite" action="{{ path('favorite_remove') }}" method="post">
					<input type="hidden" name="post_id" value="{{ post.id }}">
					<input type="hidden" name="user_id" value="{{ app.user.id }}">
					<input type="hidden" name="_token" value="{{ csrf_token('remove') }}">

					<button id="removefavoriteButton" class="btn btn-outline-warning mt-3">Remove from Favorites</button>
				</form>
			{% else %}
				<form id="addfavorite" action="{{ path('favorite_add') }}" method="POST">
					<input type="hidden" name="post_id" value="{{ post.id }}">
					<input type="hidden" name="user_id" value="{{ app.user.id }}">
					<input type="hidden" name="_token" value="{{ csrf_token('add') }}">

					<button id="addfavoriteButton" class="btn btn-outline-warning mt-3">Add to Favorites</button>
				</form>
			{% endif %}
		{% else %}
			<h3>For comment this please sign in</h3>

		{% endif %}
		<a href="{{ path('post_list') }}" class="btn btn-dark mt-2">Back to list</a>
	</div>

	<script src="{{ asset('js/comment_edit.js') }}"></script>

{% endblock %}

templates/post/test_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post List
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Post List</h1>
		<div class="list-group">
			{% for post in posts %}
				<a href="{{ path('post_show', { 'id': post.id }) }}" class="list-group-item list-group-item-action">
					<h5 class="mb-1">{{ post.title }}</h5>
					<p class="mb-1">{{ post.postText | slice(0, 100) ~ '...' }}</p>
					<small>Posted on
						{{ post.postDate | date('Y-m-d') }}</small>
					<small>Views:
						{{post.viewCount}}</small>
				</a>
			{% else %}
				<p>No posts available.</p>
			{% endfor %}
		</div>
	</div>
{% endblock %}